export const ROUTES = {
  HOME: "/",
  PRODUCT: `/product`,
  CHECKOUT: "/checkout",
  CONTACT: "/contact-us",
  TERMS: "/terms",
  PRIVACY: "/privacy",
  RETURN: "/return-policy",
  FAQ: "/faq",
  FORGET_PASSWORD: "/forget-password",
  CHANGE_PASSWORD: "/my-account/change-password",
  ACCOUNT: "/account/order",
  ACCOUNT_SETTING: "/account/information",
  ADDRESS: "/my-account/address",
  PAYMENT: "/my-account/payment",
  HELP_CENTER: "/my-account/help-center",
  LEGAL_NOTICE: "/my-account/legal-notice",
  NOTIFICATION: "/my-account/notification",
  SHOPS: "/shops",
  LOGIN: "/signin",
  SIGN_UP: "/signup",
  SEARCH: "/search",
  PRODUCTS: "/products",
  BUNDLE: "/bundles",
  CATEGORY: "/category",
  ORDER: "/complete-order",
  WISHLIST: "/my-account/wishlist",
};
