export const footer = {
  links: [
    {
      id: 1,
      title: "Privacy Policy",
      path: "/privacy",
    },
    {
      id: 2,
      title: "Terms & Services",
      path: "/terms",
    },
    {
      id: 3,
      title: "Return & Refund Policy",
      path: "/return-policy",
    },
    {
      id: 4,
      title: "Contact Us",
      path: "/contact",
    },
    {
      id: 5,
      title: "FAQ",
      path: "/faq",
    },
  ],
  payments: [
    {
      id: 1,
      path: "/",
      image: "/images/payment/mastercard.svg",
      name: "payment-master-card",
      width: 34,
      height: 20,
    },
    {
      id: 2,
      path: "/",
      image: "/images/payment/visa.svg",
      name: "payment-visa",
      width: 50,
      height: 20,
    },
    {
      id: 3,
      path: "/",
      image: "/images/payment/paytm.svg",
      name: "payment-paytm",
      width: 50,
      height: 20,
    },
    {
      id: 4,
      path: "/",
      image: "/images/payment/upi.svg",
      name: "payment-upi",
      width: 50,
      height: 20,
    },
  ],
  socials: [
    {
      id: 1,
      path: "https://www.facebook.com/",
      image: "/images/social/facebook.svg",
      name: "facebook",
      width: 20,
      height: 20,
    },
    {
      id: 2,
      path: "https://twitter.com/",
      image: "/images/social/twitter.svg",
      name: "twitter",
      width: 20,
      height: 20,
    },
    {
      id: 3,
      path: "https://www.instagram.com/",
      image: "/images/social/instagram.svg",
      name: "instagram",
      width: 20,
      height: 20,
    },
    {
      id: 4,
      path: "https://www.youtube.com/channel/UCjld1tyVHRNy_pe3ROLiLhw",
      image: "/images/social/youtube.svg",
      name: "youtube",
      width: 24,
      height: 24,
    },
    {
      id: 5,
      path: "https://www.youtube.com/channel/UCjld1tyVHRNy_pe3ROLiLhw",
      image: "/images/social/whatsapp.svg",
      name: "whatsapp",
      width: 24,
      height: 24,
    },
    {
      id: 6,
      path: "https://www.youtube.com/channel/UCjld1tyVHRNy_pe3ROLiLhw",
      image: "/images/social/telegram.svg",
      name: "telegram",
      width: 24,
      height: 24,
    },
  ],
};
